# Generated by Django 5.2.4 on 2025-09-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sampletype_alter_sample_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-12 00:00:00'),
            preserve_default=False,
        ),
    ]
