# Generated by Django 5.2.4 on 2025-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-12 00:00:00'),
            preserve_default=False,
        ),
    ]
