# Generated by Django 5.2.4 on 2025-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_patient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
