# Generated by Django 5.2.7 on 2025-11-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_alter_patient_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
