# Backend/Dockerfile
FROM python:3.13-slim

WORKDIR /app
ENV PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1

#System deps for psycopg2
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn psycopg2-binary

#Copy app
COPY . /app

# make entrypoint executable
RUN chmod +x /app/entrypoint.sh

# EXPOSE port
EXPOSE 8000

# Entrypoint will migrate & collectstatic and then run gunicorn
ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["gunicorn", "sampletracker.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "/dev/shm"]
